version: "3.7"
services: 
  messenger:
    build:
      context: ./
      dockerfile: build/docker/messenger/Dockerfile
    command: ./messenger -http-addr 0.0.0.0:3000
    env_file: env/messenger.env
    restart: on-failure
    ports: 
      - 3000:3000
  operator-1:
    build:
      context: ./
      dockerfile: build/docker/node/Dockerfile
    command: ./node
    depends_on:
      - "messenger"
    env_file: env/operator.1.env
    restart: on-failure
    ports: 
      - 8081:8081
    volumes:
      - ./keys:/keys
  operator-2:
    build:
      context: ./
      dockerfile: build/docker/node/Dockerfile
    command: ./node
    depends_on:
      - "messenger"
    env_file: env/operator.2.env
    restart: on-failure
    ports: 
      - 8082:8082
    volumes:
      - ./keys:/keys
  operator-3:
    build:
      context: ./
      dockerfile: build/docker/node/Dockerfile
    command: ./node
    depends_on:
      - "messenger"
    env_file: env/operator.3.env
    restart: on-failure
    ports: 
      - 8083:8083
    volumes:
      - ./keys:/keys
  operator-4:
    build:
      context: ./
      dockerfile: build/docker/node/Dockerfile
    command: ./node
    depends_on:
      - "messenger"
    env_file: env/operator.4.env
    restart: on-failure
    ports: 
      - 8084:8084
    volumes:
      - ./keys:/keys
  operator-5:
    build:
      context: ./
      dockerfile: build/docker/node/Dockerfile
    command: ./node
    depends_on:
      - "messenger"
    env_file: env/operator.5.env
    restart: on-failure
    ports: 
      - 8085:8085
    volumes:
      - ./keys:/keys
  operator-6:
    build:
      context: ./
      dockerfile: build/docker/node/Dockerfile
    command: ./node
    depends_on:
      - "messenger"
    env_file: env/operator.6.env
    restart: on-failure
    ports: 
      - 8086:8086
    volumes:
      - ./keys:/keys
  operator-7:
    build:
      context: ./
      dockerfile: build/docker/node/Dockerfile
    command: ./node
    depends_on:
      - "messenger"
    env_file: env/operator.7.env
    restart: on-failure
    ports: 
      - 8087:8087
    volumes:
      - ./keys:/keys